/* tslint:disable */
/* eslint-disable */
/**
 * Initry backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Test } from './test';
// May contain unused imports in some cases
// @ts-ignore
import { TestStatus } from './test-status';

/**
 * 
 * @export
 * @interface ResponseGettestbyid
 */
export interface ResponseGettestbyid {
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'nodeid'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'testRunUuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'startedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'stoppedAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponseGettestbyid
     */
    'duration'?: number;
    /**
     * 
     * @type {TestStatus}
     * @memberof ResponseGettestbyid
     */
    'status'?: TestStatus;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'log'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'logMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'stdout'?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseGettestbyid
     */
    'stderr'?: string;
}



