/* tslint:disable */
/* eslint-disable */
/**
 * Initry backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Description } from './description';
// May contain unused imports in some cases
// @ts-ignore
import { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import { Nodeid } from './nodeid';
// May contain unused imports in some cases
// @ts-ignore
import { Startedat } from './startedat';
// May contain unused imports in some cases
// @ts-ignore
import { Stoppedat } from './stoppedat';
// May contain unused imports in some cases
// @ts-ignore
import { TestStatus } from './test-status';
// May contain unused imports in some cases
// @ts-ignore
import { Testrunuuid } from './testrunuuid';

/**
 * 
 * @export
 * @interface Test
 */
export interface Test {
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'uuid': string;
    /**
     * 
     * @type {Location}
     * @memberof Test
     */
    'location'?: Location;
    /**
     * 
     * @type {Nodeid}
     * @memberof Test
     */
    'nodeid'?: Nodeid;
    /**
     * 
     * @type {Testrunuuid}
     * @memberof Test
     */
    'testRunUuid'?: Testrunuuid;
    /**
     * 
     * @type {Description}
     * @memberof Test
     */
    'description'?: Description;
    /**
     * 
     * @type {Startedat}
     * @memberof Test
     */
    'startedAt'?: Startedat;
    /**
     * 
     * @type {Stoppedat}
     * @memberof Test
     */
    'stoppedAt'?: Stoppedat;
    /**
     * 
     * @type {TestStatus}
     * @memberof Test
     */
    'status'?: TestStatus;
}

