/* tslint:disable */
/* eslint-disable */
/**
 * Initry backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TestStatus } from './test-status';

/**
 * 
 * @export
 * @interface Test
 */
export interface Test {
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'location'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'nodeid'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'testRunUuid'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'startedAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'stoppedAt'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    'duration'?: number | null;
    /**
     * 
     * @type {TestStatus}
     * @memberof Test
     */
    'status'?: TestStatus | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'log'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'logMessage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'stdout'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    'stderr'?: string | null;
}



