/* tslint:disable */
/* eslint-disable */
/**
 * Initry backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TestStatus = {
    Running: 'RUNNING',
    Passed: 'PASSED',
    Failed: 'FAILED',
    Skipped: 'SKIPPED',
    ExpectedPassed: 'EXPECTED_PASSED',
    ExpectedFailed: 'EXPECTED_FAILED',
    Error: 'ERROR'
} as const;

export type TestStatus = typeof TestStatus[keyof typeof TestStatus];



