version: '3.8'

services:

  backend:
    image: backend:latest
    build:
      context: ./backend
    ports:
      - ${INITRY_API_EXTERNAL_PORT}:8000
      - ${INITRY_GRPC_EXTERNAL_PORT}:50051
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - ${INITRY_FRONTEND_EXTERNAL_PORT}:3000
    depends_on:
      - backend

  celery-worker:
    build:
      context: ./backend
    command: celery -A tasks.tasks worker -l INFO
    depends_on:
      - backend

  redis:
    image: "redis:7.2.4"
    ports:
      - "6379:6379"

