# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import responses_pb2 as responses__pb2
import tests_pb2 as tests__pb2


class TestsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTests = channel.unary_unary(
                '/TestsService/CreateTests',
                request_serializer=tests__pb2.CreateTestsRequest.SerializeToString,
                response_deserializer=responses__pb2.StatusOk.FromString,
                )


class TestsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTests': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTests,
                    request_deserializer=tests__pb2.CreateTestsRequest.FromString,
                    response_serializer=responses__pb2.StatusOk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TestsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TestsService/CreateTests',
            tests__pb2.CreateTestsRequest.SerializeToString,
            responses__pb2.StatusOk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
