/* tslint:disable */
/* eslint-disable */
/**
 * Initry backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { TestRunsTotalData } from '../models';
// @ts-ignore
import { TestRunsTrend } from '../models';
/**
 * StatsApi - axios parameter creator
 * @export
 */
export const StatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Total Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestRunsTotalData: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/stats/total-data`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Trend
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrendData: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/stats/trend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatsApi - functional programming interface
 * @export
 */
export const StatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Total Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTestRunsTotalData(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TestRunsTotalData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTestRunsTotalData(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.getTestRunsTotalData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Trend
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrendData(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TestRunsTrend>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrendData(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.getTrendData']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatsApi - factory interface
 * @export
 */
export const StatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Total Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTestRunsTotalData(options?: any): AxiosPromise<TestRunsTotalData> {
            return localVarFp.getTestRunsTotalData(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Trend
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrendData(options?: any): AxiosPromise<TestRunsTrend> {
            return localVarFp.getTrendData(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatsApi - interface
 * @export
 * @interface StatsApi
 */
export interface StatsApiInterface {
    /**
     * 
     * @summary Get Total Data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getTestRunsTotalData(options?: RawAxiosRequestConfig): AxiosPromise<TestRunsTotalData>;

    /**
     * 
     * @summary Get Trend
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApiInterface
     */
    getTrendData(options?: RawAxiosRequestConfig): AxiosPromise<TestRunsTrend>;

}

/**
 * StatsApi - object-oriented interface
 * @export
 * @class StatsApi
 * @extends {BaseAPI}
 */
export class StatsApi extends BaseAPI implements StatsApiInterface {
    /**
     * 
     * @summary Get Total Data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApi
     */
    public getTestRunsTotalData(options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).getTestRunsTotalData(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Trend
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApi
     */
    public getTrendData(options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).getTrendData(options).then((request) => request(this.axios, this.basePath));
    }
}

